#!/usr/bin/python'
#importing request from form page
import cgi
#saving data to variable
form = cgi.FieldStorage()

firstName = form.getvalue('firstName')
lastName = form.getvalue('lastName')
school = form.getvalue('school')
print ("Content-Type:text/html\n")
print("")
print("")
print("<head>")
print("<style>")
print("table, td, th {border: 2px solid black;}")
print("body {align-content: center;}")
print("</style>")
print("</head>")
print("<body>")
print("WDV495 EMERGING TECH")
print("<h1>This page displays the results of the Server side Python Page</h1>")
print("<table>")
print("<tr>")
print("<th>First Name</th>")
print("<th>Last Name</th>")
print("<th>School</th>")
print("</tr>")
print("<tr>")
print("<td>")
print(firstName)
print("</td>")
print("<td>")
print(lastName)
print("</td>")
print("<td>")
print(school)
print("</td>")
print("</tr>")
print("</table>")
print("</body>")
print("</html>")
